package com.redis.socialmediatracker.slack;

import com.redis.socialmediatracker.agent.reportagent.ReportResult;

import java.util.List;

/**
 * Formats ReportResult objects into Slack's mrkdwn format with proper styling.
 * Slack mrkdwn reference: https://api.slack.com/reference/surfaces/formatting
 */
public class SlackReportFormatter {

    /**
     * Convert a ReportResult to a beautifully formatted Slack message.
     * Uses Slack's mrkdwn format with emojis, bold text, and proper structure.
     */
    public static String toSlackFormat(ReportResult reportResult) {
        if (reportResult == null || reportResult.getReport() == null) {
            return "📊 *Redis Social Trends Report*\n\n_No report data available._";
        }

        var report = reportResult.getReport();
        StringBuilder slack = new StringBuilder();

        // Title with emoji
        slack.append("📊 *")
                .append(report.getTitle() != null ? report.getTitle() : "Redis Social Trends Report")
                .append("*\n\n");

        // Timeframe as a quote block
        if (reportResult.getTimeframe() != null) {
            slack.append("> 📅 *Timeframe:* ").append(reportResult.getTimeframe()).append("\n\n");
        }

        // Divider
        slack.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n");

        // Summary section with emoji
        if (report.getSummary() != null && !report.getSummary().isBlank()) {
            slack.append("📝 *Summary*\n")
                    .append(formatContent(report.getSummary()))
                    .append("\n\n");
        }

        // Sections
        if (report.getSections() != null && !report.getSections().isEmpty()) {
            for (int i = 0; i < report.getSections().size(); i++) {
                ReportResult.Section section = report.getSections().get(i);
                
                // Section heading with emoji
                String emoji = getSectionEmoji(section.getHeading(), i);
                slack.append(emoji).append(" *").append(section.getHeading()).append("*\n");
                
                // Section content
                slack.append(formatContent(section.getContent())).append("\n");

                // References if available
                List<ReportResult.Reference> refs = section.getReferences();
                if (refs != null && !refs.isEmpty()) {
                    slack.append("\n_Sources:_\n");
                    for (ReportResult.Reference ref : refs) {
                        slack.append("• ");
                        
                        // Format as clickable link
                        if (ref.getUrl() != null && !ref.getUrl().isBlank()) {
                            String linkText = ref.getPlatform() != null ? ref.getPlatform() : "Link";
                            slack.append("<").append(ref.getUrl()).append("|").append(linkText).append(">");
                        }
                        
                        // Add description if available
                        if (ref.getDescription() != null && !ref.getDescription().isBlank()) {
                            slack.append(" — ").append(ref.getDescription());
                        }
                        
                        slack.append("\n");
                    }
                }
                
                slack.append("\n");
            }
        } else {
            slack.append("_No sections available in this report._\n\n");
        }

        // Footer
        slack.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
        slack.append("_Generated by Redis Social Media Tracker_ 🤖");

        return slack.toString();
    }

    /**
     * Format content text for Slack:
     * - Convert **bold** to *bold*
     * - Convert _italic_ to _italic_ (already compatible)
     * - Convert bullet points to proper format
     * - Add proper spacing
     */
    private static String formatContent(String content) {
        if (content == null) {
            return "";
        }
        
        return content
                // Convert markdown bold to Slack bold
                .replaceAll("\\*\\*(.*?)\\*\\*", "*$1*")
                // Convert markdown italic to Slack italic (already compatible)
                // Ensure bullet points are properly formatted
                .replaceAll("^- ", "• ")
                .replaceAll("\n- ", "\n• ")
                // Add slight indentation to bullet points
                .replaceAll("\n• ", "\n  • ");
    }

    /**
     * Get an appropriate emoji for a section based on its heading.
     */
    private static String getSectionEmoji(String heading, int index) {
        if (heading == null) {
            return "📌";
        }
        
        String lower = heading.toLowerCase();
        
        // Topic-related
        if (lower.contains("topic") || lower.contains("discussion")) {
            return "💬";
        }
        // Trend-related
        if (lower.contains("trend") || lower.contains("popular")) {
            return "📈";
        }
        // Insight-related
        if (lower.contains("insight") || lower.contains("analysis")) {
            return "💡";
        }
        // Recommendation-related
        if (lower.contains("recommend") || lower.contains("action")) {
            return "🎯";
        }
        // Sentiment-related
        if (lower.contains("sentiment") || lower.contains("mood")) {
            return "😊";
        }
        // Key findings
        if (lower.contains("key") || lower.contains("finding") || lower.contains("takeaway")) {
            return "🔑";
        }
        
        // Default emojis based on position
        String[] defaultEmojis = {"🔹", "🔸", "🔷", "🔶", "🟦", "🟧"};
        return defaultEmojis[index % defaultEmojis.length];
    }
}

